#!/usr/bin/with-contenv sh

for template_file in /etc/consul/conf.d/*.tpl
do
    echo "transform ${template_file} to $(dirname "$template_file")/$(basename "$template_file" .tpl).json"
    gomplate --file="${template_file}" --out="$(dirname "$template_file")/$(basename "$template_file" .tpl).json"
done